Add explicit Xcode check in mac intel

diff --git a/.github/workflows/ccpp_mac_rc.yml b/.github/workflows/ccpp_mac_rc.yml
--- a/.github/workflows/ccpp_mac_rc.yml
+++ b/.github/workflows/ccpp_mac_rc.yml
@@ -15,7 +15,21 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    - name: Select Xcode 15
+      run: |
+        ls -1 /Applications | grep -E '^Xcode_'
+        if [ -d "/Applications/Xcode_15.0.app" ]; then
+          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
+        elif [ -d "/Applications/Xcode_15.4.app" ]; then
+          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
+        else
+          echo "Xcode 15.x not found on this runner."
+          exit 1
+        fi
 
+        xcodebuild -version
+        xcode-select -p
+        clang --version
     - name: Show runner info
       run: |
         echo "Runner architecture:"
@@ -75,7 +89,21 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    - name: Select Xcode 15
+      run: |
+        ls -1 /Applications | grep -E '^Xcode_'
+        if [ -d "/Applications/Xcode_15.0.app" ]; then
+          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
+        elif [ -d "/Applications/Xcode_15.4.app" ]; then
+          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
+        else
+          echo "Xcode 15.x not found on this runner."
+          exit 1
+        fi
 
+        xcodebuild -version
+        xcode-select -p
+        clang --version
     - name: Show runner info
       run: |
         echo "Runner architecture:"
